#pragma checksum "..\..\Car.xaml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "0F6F720684AD3AEFAEAA913B42778AEC8B3FB299F4DCF95B8DD4746E51DE7621"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WpfApp1;


namespace WpfApp1 {
    
    
    /// <summary>
    /// Car
    /// </summary>
    public partial class Car : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 16 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TxtPurchacePrice;
        
        #line default
        #line hidden
        
        
        #line 17 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtCarModel;
        
        #line default
        #line hidden
        
        
        #line 18 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtDepositCar;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtIntrestCar;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtInsuranceCar;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button txtCalculateCar;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker dateTimePickerC;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txtYearsCar;
        
        #line default
        #line hidden
        
        
        #line 25 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListView listView;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnHome;
        
        #line default
        #line hidden
        
        
        #line 33 "..\..\Car.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btnClear;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WpfApp1;component/car.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\Car.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.TxtPurchacePrice = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.txtCarModel = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.txtDepositCar = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.txtIntrestCar = ((System.Windows.Controls.TextBox)(target));
            return;
            case 5:
            this.txtInsuranceCar = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.txtCalculateCar = ((System.Windows.Controls.Button)(target));
            
            #line 21 "..\..\Car.xaml"
            this.txtCalculateCar.Click += new System.Windows.RoutedEventHandler(this.txtCalculateC_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.dateTimePickerC = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 8:
            this.txtYearsCar = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.listView = ((System.Windows.Controls.ListView)(target));
            return;
            case 10:
            this.btnHome = ((System.Windows.Controls.Button)(target));
            
            #line 32 "..\..\Car.xaml"
            this.btnHome.Click += new System.Windows.RoutedEventHandler(this.btnHome_Click_1);
            
            #line default
            #line hidden
            return;
            case 11:
            this.btnClear = ((System.Windows.Controls.Button)(target));
            
            #line 33 "..\..\Car.xaml"
            this.btnClear.Click += new System.Windows.RoutedEventHandler(this.btnClear_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

